name: build
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: setup
        run: ./gradlew setup
      - name: build
        run: ./gradlew buildCatServer
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: projects/forge/build/libs

